"""Auto-reply pipeline for Telegram Business messages."""

import asyncio
import logging

from aiogram import Bot, Router
from aiogram.types import Message

from database.repository import BotRepository
from services.ai import generate_reply
from services.business import cache_message_media, skip_reply_reason
from services.business.skip_policy import SKIP_AI_DISABLED, SKIP_BLACKLISTED

logger = logging.getLogger(__name__)
router = Router(name="business_messages")

DEFAULT_SYSTEM_PROMPT = (
    "Ты — умный и вежливый ИИ-ассистент, помогающий отвечать на сообщения в "
    "профиле Telegram."
)


def _parse_delay(raw_value: str | None) -> int:
    """Parse the configured reply delay, clamping invalid values to ``0``."""
    try:
        return max(0, int(raw_value or "0"))
    except (ValueError, TypeError) as e:
        logger.warning("Invalid reply_delay_seconds value %r: %s", raw_value, e)
        return 0


async def _log_skip(
    repo: BotRepository,
    *,
    skip_reason: str,
    connection_id: str,
    chat_id: int,
    sender_id: int,
    message_text: str,
) -> None:
    """Persist a skipped interaction so admin stats stay accurate."""
    if skip_reason not in {SKIP_AI_DISABLED, SKIP_BLACKLISTED}:
        return
    await repo.logs.log_interaction(
        connection_id=connection_id,
        chat_id=chat_id,
        sender_id=sender_id,
        message_text=message_text,
        reply_text="[IGNORED: BLACKLISTED]" if skip_reason == SKIP_BLACKLISTED else None,
    )


@router.business_message()
async def handle_business_message(message: Message, repo: BotRepository, bot: Bot) -> None:
    """Archive a Business message and send an AI reply when allowed."""
    if message.from_user is None:
        logger.debug("Skipping business message without a sender.")
        return

    connection_id = message.business_connection_id
    chat_id = message.chat.id
    sender_id = message.from_user.id
    sender_name = message.from_user.full_name
    message_text = message.text or message.caption or ""

    media_file_path, media_type = await cache_message_media(message, bot)

    logger.info(
        "Received business message: Connection=%s, Chat=%s, Sender=%s, TextLength=%s, MediaType=%s",
        connection_id,
        chat_id,
        sender_id,
        len(message_text),
        media_type,
    )

    await repo.archive.save_message(
        message_id=message.message_id,
        chat_id=chat_id,
        connection_id=connection_id,
        sender_id=sender_id,
        sender_name=sender_name,
        message_text=message_text,
        media_file_path=media_file_path,
        media_type=media_type,
    )

    settings_map = await repo.settings.all()

    skip_reason = await skip_reply_reason(message_text, sender_id, repo, settings_map)
    if skip_reason:
        await _log_skip(
            repo,
            skip_reason=skip_reason,
            connection_id=connection_id,
            chat_id=chat_id,
            sender_id=sender_id,
            message_text=message_text,
        )
        return

    system_prompt = settings_map.get("system_prompt", DEFAULT_SYSTEM_PROMPT)
    delay = _parse_delay(settings_map.get("reply_delay_seconds"))

    reply_content = await generate_reply(
        repo,
        message_text=message_text,
        system_prompt=system_prompt,
        settings_map=settings_map,
        chat_id=chat_id,
    )

    if not reply_content:
        logger.warning("No reply content generated by AI service.")
        return

    if delay > 0:
        logger.info("Delaying reply by %s seconds.", delay)
        await asyncio.sleep(delay)

    try:
        await message.answer(text=reply_content)
        logger.info("Successfully sent business reply to Chat=%s", chat_id)

        await repo.logs.log_interaction(
            connection_id=connection_id,
            chat_id=chat_id,
            sender_id=sender_id,
            message_text=message_text,
            reply_text=reply_content,
        )
    except Exception as e:
        logger.error(
            "Failed to send business reply message. Ensure the bot has can_reply permission. Error: %s",
            e,
            exc_info=True,
        )
